### PR TITLE
Adds the ability to get images at various ratios

### PR DESCRIPTION
**Pull request by doingandlearning**
This PR is a response to this issue - https://github.com/colbyfayock/raycast-cloudinary/issues/3

I've extracted the image generation to lib/extension.ts which I think was the original intention of that file.

I've added in an option for each of the resolutions requested in the issue.

### CODE REVIEW

**Comment by colbyfayock** [comment]
awesome thanks for putting this together!

i'm getting an error though when spinning this up locally

image

im super confused though as i can't see how your changes would have impacted this at all, yet i can't reproduce on `main`

Resource at this point is potentially undefined:

```
console.log('resource', resource)
  const listItems = getUploadSuccessItems(resource as Asset);
```
and as im typing this, looked at the diff, and i think its because we were checking for `resource?.public_id` 

```
const optimizedUrl =
    resource?.public_id
```

where that check isn't available on the `asset` object in the abstracted function

is that easy for you to add a check somewhere that asset exists while it loads? otherwise i can push a commit and handle it, lmk!

**Comment by colbyfayock** [comment]
@doingandlearning any luck?

**Comment by doingandlearning** [comment]
Sorry - I don't keep up on my GH notifications and missed this.

So, this works now - passing the asset typed through to another function caused some issues when it wasn't ready yet. 

The resolutions are using crop set to fill - this mightn't be ideal for all use cases. Not sure if there is a nicer way to handle this. We could make the list much longer having each crop style for each resolution ... easy to implement, not sure it's a great UX.

**Comment by colbyfayock** [comment]
@all-contributors please add @doingandlearning for code

**Comment by colbyfayock** [comment]
@doingandlearning congrats on the merged PR! since it was opened during Hacktoberfest and merged shortly after, you're eligible for some free swag. Please email [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your Github username and a link to this PR where we'll follow up with you there.

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Pull request merged**
