### PR TITLE
Automatically run linting and formatting on commit

### LINKED ISSUE #1: [Feature] Automatically run linting and formatting on commit
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

On commit, run the formatter then the linter to avoid committing changes that would potentially break builds.

## **Describe the solution you'd like**

https://typicode.github.io/husky/

## **Describe alternatives you've considered**

Doing this on commit creates a shorter feedback loop.

### PR DESCRIPTION
**Pull request by daniel-shuy**
Closes #1

Uses Husky to run ESLint and Prettier on commit

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey @daniel-shuy ran into a small issue

image

looks like this is a common occurrence: https://github.com/typicode/husky/issues/1177

is this something individuals would have to do on their own? or can we change the file in the repo to make it easier for people to run ?

**Comment by daniel-shuy** [comment]
Seems like Git for Windows doesn't preserve file permissions. What's odd is I was using WSL. I've chmod the file as `755`, it should work now

**Comment by colbyfayock** [comment]
yup! it ran perfectly

the only thing now im unsure of is it continues to commit without the changed files 🤔 

image

do you think this is something addressable? 

ive used https://github.com/okonet/lint-staged in the past to help with this kind of thing

**Comment by daniel-shuy** [comment]
You were right, `lint-staged` was required to commit changed files, I've added it

**Comment by colbyfayock** [comment]
works perfectly!! thanks @daniel-shuy

**Comment by colbyfayock** [comment]
@all-contributors please add @daniel-shuy for infra, tool

**Comment by daniel-shuy** [comment]
Yay! Thanks for the guidance!

**Comment by colbyfayock** [comment]
https://github.com/colbyfayock/raycast-cloudinary/pull/2#issuecomment-1747393493

hey @daniel-shuy, haven't seen you reach out about the Hacktoberfest swag. please do as the cutoff to claim swag will be end of day this Friday 11/17. thanks

**Comment by daniel-shuy** [comment]
@colbyfayock oops I forgot, thanks for the reminder!

**Pull request merged**
